# See https://pre-commit.com for more information

default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--check"]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--check"]
        language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--ignore=E203,E266,F401,W503", "--max-line-length=88"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--namespace-packages"]
  
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen