[build-system]
requires = ["setuptools", "wheel",  "setuptools_scm>=6.0"]

# Including this section is same as 'use_scm_version=True' in setup.py
# See https://github.com/pypa/setuptools_scm for guidance
[tool.setuptools_scm]

[tool.isort]
profile = "black"
